services:
  client-service:
    container_name: client-service
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/client_service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@postgres:5432/mydb"
      MESSAGE_BROKER_HOST_URL: "rabbitmq"
    depends_on:
      - rabbitmq
      - postgres

  model-service:
    container_name: model-service
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/model_service/Dockerfile
    environment:
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@postgres:5432/mydb"
      MESSAGE_BROKER_HOST_URL: "rabbitmq"
    depends_on:
      - rabbitmq
      - postgres

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      BACKEND_URL: "http://client-service:8000"
    ports:
      - "8501:8501"
    depends_on:
      - client-service
      - model-service

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - client-service

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana:/etc/grafana
    depends_on:
      - prometheus