[tox]
minversion = 4.24.2
skipsdist = true
envlist =
    tests
    flake8
    mypy

[testenv]
passenv = *
usedevelop = true
setenv = PYTHONDONTWRITEBYTECODE=1

[testenv:tests]
passenv = *
deps = uv == 0.6.5
commands =
    uv sync
    uv run pytest -k "not skip_tox" --cov-report xml

[testenv:flake8]
usedevelop = false
deps = 
    flake8 == 7.1.2
    flake8-pyproject == 1.2.3
commands = flake8 src tests

[testenv:mypy]
usedevelop = false
deps = 
    mypy >= 1.15.0
    types-requests >= 2.32.0.20250328
commands = mypy src
